### PR TITLE
Add battery info

### PR DESCRIPTION
**Pull request by sxy-sun**
1. Added analog reading to OMNI firmware, need to test
2. Data structure changes to print.c to get rid of compile warning
3. typo bugfix in comms.c

### CODE REVIEW

**Comment by sxy-sun** [comment]
This doesn't work on OMNI. The code is reading from V Motor instead of V Input. When the mbot is using 6 Volts motors, the voltage cap is on 6V and the code is measuring V motor on the board. Unless the control board get updated, OMNI cannot have the battery info feature.

**Comment by sxy-sun** [comment]
This doesn't work on OMNI. The code is reading from V Motor instead of V Input. When the mbot is using 6 Volts motors, the voltage cap is on 6V and the code is measuring V motor on the board. Unless the control board get updated, OMNI cannot have the battery info feature.

**Comment by sxy-sun** [comment]
New plan: Add code to check if the battery voltage was below a reasonable level. If the voltage is 6ish or lower, display it as motor voltage.

**Review by janapavlasek — APPROVED** [review]

**Comment by janapavlasek** [comment]
Tested on the Omni with 6V motors, works!

**Pull request merged**
